// <auto-generated />
using System;
using DAL.Models.models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(dbClass))]
    [Migration("20250706124249_AddIsActiveToJob")]
    partial class AddIsActiveToJob
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.models.Company", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.HasKey("Code")
                        .HasName("PK__Company__A25C5AA6DBADD1B8");

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("DAL.Models.models.Job", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("CompanyID");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Field")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinYearsExperience")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresDegree")
                        .HasColumnType("bit");

                    b.Property<double>("WorkHours")
                        .HasColumnType("float");

                    b.HasKey("Code")
                        .HasName("PK__tmp_ms_x__A25C5AA656C24301");

                    b.HasIndex(new[] { "CompanyId" }, "IX_Job_CompanyID");

                    b.ToTable("Job", (string)null);
                });

            modelBuilder.Entity("DAL.Models.models.JobOffer", b =>
                {
                    b.Property<int>("OffersCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsApplied")
                        .HasColumnType("bit");

                    b.Property<int>("JobCode")
                        .HasColumnType("int");

                    b.Property<double>("MatchingScore")
                        .HasColumnType("float");

                    b.HasKey("OffersCode")
                        .HasName("PK__JobOffer__F4BD6BD8585C6A1F");

                    b.HasIndex(new[] { "CandidateId" }, "IX_JobOffer_CandidateId");

                    b.HasIndex(new[] { "JobCode" }, "IX_JobOffer_JobCode");

                    b.ToTable("JobOffer", (string)null);
                });

            modelBuilder.Entity("DAL.Models.models.JobSeeker", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("DailyWorkHours")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Field")
                        .HasColumnType("int");

                    b.Property<bool>("HasDegree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SirName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__tmp_ms_x__3214EC07B4ACE1BA");

                    b.ToTable("JobSeeker", (string)null);
                });

            modelBuilder.Entity("DAL.Models.models.UserPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_UserPasswords_UserId")
                        .IsUnique();

                    b.ToTable("UserPasswords");
                });

            modelBuilder.Entity("DAL.Models.models.Job", b =>
                {
                    b.HasOne("DAL.Models.models.Company", "Company")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_Job_ToTable");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DAL.Models.models.JobOffer", b =>
                {
                    b.HasOne("DAL.Models.models.JobSeeker", "Candidate")
                        .WithMany("JobOffers")
                        .HasForeignKey("CandidateId")
                        .IsRequired()
                        .HasConstraintName("FK_JobOffer_ToTable");

                    b.HasOne("DAL.Models.models.Job", "JobCodeNavigation")
                        .WithMany("JobOffers")
                        .HasForeignKey("JobCode")
                        .IsRequired()
                        .HasConstraintName("FK_JobOffer_ToTable_1");

                    b.Navigation("Candidate");

                    b.Navigation("JobCodeNavigation");
                });

            modelBuilder.Entity("DAL.Models.models.UserPassword", b =>
                {
                    b.HasOne("DAL.Models.models.Company", "CompanyUser")
                        .WithOne("UserPassword")
                        .HasForeignKey("DAL.Models.models.UserPassword", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.models.JobSeeker", "SeekerUser")
                        .WithOne("UserPassword")
                        .HasForeignKey("DAL.Models.models.UserPassword", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyUser");

                    b.Navigation("SeekerUser");
                });

            modelBuilder.Entity("DAL.Models.models.Company", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("UserPassword");
                });

            modelBuilder.Entity("DAL.Models.models.Job", b =>
                {
                    b.Navigation("JobOffers");
                });

            modelBuilder.Entity("DAL.Models.models.JobSeeker", b =>
                {
                    b.Navigation("JobOffers");

                    b.Navigation("UserPassword");
                });
#pragma warning restore 612, 618
        }
    }
}
